<a href="https://colab.research.google.com/github/samrat-rm/Brain-Cache/blob/main/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## What is Numpy ?
NumPy stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Why NumPy?

You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. Vectorization aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called broadcasting.

## Vectorization

Vectorization (like in NumPy) avoids being slow like Python by pushing the whole operation into fast low-level C code.

# Broadcasting

Broadcasting allows NumPy to perform operations between arrays of different shapes by automatically “stretching” the smaller array to match the larger one—without making actual copies.

It makes array math faster and cleaner by avoiding manual loops.

In [ ]:
# Example

import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b

print(result)

[[11 22 33]
 [14 25 36]]

NumPy treated b like this internally:

In [ ]:
[[10, 20, 30],
 [10, 20, 30]]

[[10, 20, 30], [10, 20, 30]]


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

#### Setup

In [ ]:
!python --version

Python 3.12.13

In [ ]:
!pip install numpy
!pip install pandas

import numpy as np
import pandas as pd

print(np.__version__ , pd.__version__)

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
2.0.2 2.2.2


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

# DataTypes and Attributes

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Note: Important to remember the main type in NumPy is ndarray, even seemingly different kinds of arrays are still ndarray's. This means an operation you do on one array, will work on another.

In [ ]:

# Vector
a1 = np.array([1,2,3])

# 2D Matrix
a2 = np.array([[1,2],[4.0,5.3]])

# 3D Matrix
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [ ]:
a1.shape , a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
# Expected (1,3) but got (3,)
# If you want shape (1,3), you must make it explicitly 2D:
a4 = np.array([[1,2,3]])
a4.shape, a4.ndim, a4.dtype, a4.size, type(a4)

((1, 3), 2, dtype('int64'), 3, numpy.ndarray)

In [ ]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 2), 2, dtype('float64'), 4, numpy.ndarray)

In [ ]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

Key terms:

- Array - A list of numbers, can be multi-dimensional.
- Scalar - A single number (e.g. 7).
- Vector - A list of numbers with 1-dimension (e.g. `np.array([1, 2, 3]))`.
- Matrix - A (usually) multi-dimensional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]]))`.

### pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.

In [ ]:
df = pd.DataFrame(np.random.randint(10, size=(5,3)),columns=['a','b','c'])
df

   a  b  c
0  3  2  6
1  5  6  9
2  9  4  9
3  6  1  6
4  5  4  0

In [ ]:
a2

array([[1. , 2. ],
       [4. , 5.3]])

In [ ]:
df2 = pd.DataFrame(a2)
df2

     0    1
0  1.0  2.0
1  4.0  5.3

In [ ]:
type(df)

pandas.core.frame.DataFrame


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

## Creating arrays

- `np.array()`
- `np.ones()`
- `np.zeros()`
- `np.random.rand(5, 3)`
- `np.random.randint(10, size=5)`
- `np.random.seed()` - pseudo random numbers
- Searching the documentation example (finding `np.unique()` and using it)

### `np.array()`

In [ ]:
arr = np.array([1,2,4])
arr

array([1, 2, 4])

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### `np.ones()`

In [ ]:
arr2 = np.ones((10))
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr2 = np.ones((2,5))
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
arr2.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])


### `np.zeros()`

In [ ]:
arr3 = np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
arr3.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr3 = np.zeros((2,3,5))
arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])


### `np.arange()`

In [ ]:
arr4 = np.arange(5,13,1.5) # (start,step,step)
arr4

array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5])


### `np.random.rand()`

In [ ]:
arr5 = np.random.rand(5,3) # 0 to 1
arr5

array([[0.1226573 , 0.57220853, 0.65694926],
       [0.09208411, 0.49914133, 0.59317394],
       [0.77278438, 0.22748605, 0.69562662],
       [0.04360482, 0.86280788, 0.04364976],
       [0.33290421, 0.78838547, 0.71418231]])


### `np.random.randint()`

In [ ]:
arr5 = np.random.randint(5,15,size=(2,3,4)) # (low, high=None, size=None)
arr5

array([[[12,  9,  9,  5],
        [ 8,  6,  5, 10],
        [11,  5, 10, 12]],

       [[12,  5, 12,  5],
        [ 7,  9,  8,  5],
        [ 7, 14, 12, 11]]])

### `np.random.random()`

In [ ]:
arr6 = np.random.random((3,5))
arr6

array([[0.98397416, 0.49318013, 0.98934482, 0.68851682, 0.10540053],
       [0.31958958, 0.98714343, 0.73842487, 0.39546772, 0.81548745],
       [0.03728442, 0.094968  , 0.54316792, 0.80931954, 0.78504755]])

`np.random.random(x,y)` and `np.random.random((x,y))` only the syntax is differnt. Function is same.


### `np.random.seed()`

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [ ]:
# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

In [ ]:
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])


Let's see it in action again, we'll stay consistent and set the random seed to 0.

In [ ]:
np.random.seed(0)
np.random.randint(10,size=(5,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [ ]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

   0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1


### `np.unique()`

In [ ]:
np.unique(df)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note :**

`np.unique()` is designed for NumPy arrays, but a pandas DataFrame can still work because it can be automatically converted to a NumPy array.

```
np.unique(df)
```

Numpy internally converts into

```
np.unique(df.values)
# or
np.unique(df.to_numpy())
```


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

# Indexing

###  Viewing Array and Matrices

Remember, because arrays and matrices are both `ndarray`'s, they can be viewed in similar ways.

In [ ]:
a1 , a2 , a3

(array([1, 2, 3]),
 array([[1. , 2. ],
        [4. , 5.3]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

**Array** shapes are always listed in the format `(row, column, n, n, n...)` where `n` is optional extra dimensions.

In [ ]:
a1[0]

np.int64(1)

In [ ]:
a2[0]

array([1., 2.])

In [ ]:
a2[:2] # first 2 values -> 0,1 index

array([[1. , 2. ],
       [4. , 5.3]])

In [ ]:
a3[:1,:2,:2]

array([[[1, 2],
        [4, 5]]])




> NumPy arrays get printed from outside to inside. This means the number at the end of the shape comes first, and the number at the start of the shape comes last.Add blockquote

In [ ]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [ ]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

`a4`'s shape is (2, 3, 4, 5), this means it gets displayed like so:
* Inner most array = size 5
* Next array = size 4
* Next array = size 3
* Outer most array = size 2

In [ ]:
# get first 4 number of each vector

a4[:,:,:,:3]

array([[[[6, 7, 7],
         [5, 9, 8],
         [3, 0, 3],
         [2, 3, 8]],

        [[3, 3, 7],
         [9, 9, 0],
         [3, 2, 7],
         [0, 4, 5]],

        [[8, 4, 1],
         [8, 1, 1],
         [9, 3, 6],
         [0, 3, 5]]],


       [[[4, 6, 4],
         [4, 4, 8],
         [7, 5, 5],
         [5, 9, 3]],

        [[0, 1, 2],
         [0, 3, 2],
         [5, 9, 0],
         [2, 9, 2]],

        [[2, 3, 4],
         [9, 1, 4],
         [2, 3, 0],
         [0, 6, 3]]]])


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

## Manipulating and comparing arrays

* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than Python's `.sum()` for NumPy arrays
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T`
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Arithematic

In [ ]:
a1

array([1, 2, 3])

In [ ]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [ ]:
a1+ones

array([2., 3., 4.])

In [ ]:
a1-ones

array([0., 1., 2.])

In [ ]:
a1*ones

array([1., 2., 3.])

In [ ]:
a1.shape, a2.shape

((3,), (2, 2))

Note: (3,1) because its scaler value. To get (1,3) use `a1=np.array([[1,2,3]])`

In [ ]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [ ]:
a1.shape

(1, 3)

In [ ]:
a1*a2

ValueError: operands could not be broadcast together with shapes (1,3) (2,2)

In [ ]:
a1 = np.array([1,2,3])
a1.shape

(3,)

In [ ]:
a1*a2

ValueError: operands could not be broadcast together with shapes (3,) (2,2)

Error because Broadcasting rule is not being followed. Broadcasting checks shapes from right to left.

Dimensions are compatible if:

1. they are equal

**Example :**
```
A.shape = (2, 3)
B.shape = (2, 3)
```
2. or one of them is 1

**Example :**

```
A.shape = (2, 3)
B.shape = (1, 3)
```

### Broadcasting

- What is broadcasting?
    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
    
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

In [ ]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2.shape

(2, 3)

In [ ]:
a1.shape

(3,)

In [ ]:
a1*a2 # follows broadcasting rule

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [ ]:
a1*2

array([2, 4, 6])

In [ ]:
a2-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [ ]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [ ]:
a1/ones

array([1., 2., 3.])

In [ ]:
a1-a2

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [ ]:
a1//a2

array([[1, 1, 1],
       [0, 0, 0]])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a1**2

array([1, 4, 9])

In [ ]:
# or use
np.square(a1)

array([1, 4, 9])

In [ ]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### Aggregate

In [ ]:
sum(a1)

np.int64(6)

In [ ]:
# or
np.sum(a1)

np.int64(6)

**Tip:** Use NumPy's `np.sum()` on NumPy arrays and Python's `sum()` on Python `list`s.

In [ ]:
big_array = np.random.rand(100000)
big_array.size, type(big_array)

(100000, numpy.ndarray)

In [ ]:
%timeit sum(big_array) # Python sum()
%timeit np.sum(big_array) # NumPy np.sum()

10.6 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
34.5 µs ± 898 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

Notice `np.sum()` is faster on the Numpy array (`numpy.ndarray`) than Python's `sum()`.

Now let's try it out on a Python list.

In [ ]:
import random
big_list = [random.randint(0,10) for i in range(100000)]
len(big_list),type(big_list)

(100000, list)

In [ ]:
%timeit sum(big_list)
%timeit np.sum(big_list)

979 µs ± 306 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.48 ms ± 95.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

1 second

milliseconds = 1000 ms

microseconds = 1,000,000 µs

nano seconds = 1,000,000,000 ns

NumPy's `np.sum()` is still fast but Python's `sum()` is faster on Python `list`s.

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

**What's mean?**

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

**What's standard deviation?**

[Standard deviation](https://www.mathsisfun.com/data/standard-deviation.html) is a measure of how spread out numbers are.

**What's variance?**

The [variance](https://www.mathsisfun.com/data/standard-deviation.html) is the averaged squared differences of the mean.

In [ ]:
np.mean(a2)

np.float64(3.5)

In [ ]:
np.max(a2)

np.int64(6)

In [ ]:
np.min(a2)

np.int64(1)

In [ ]:
np.var(a2)

np.float64(2.9166666666666665)

In [ ]:
np.sqrt(np.var(a2))

np.float64(1.707825127659933)

In [ ]:
np.std(a2)

np.float64(1.707825127659933)

To work it out, you:
1. Work out the mean
2. For each number, subtract the mean and square the result
3. Find the average of the squared differences

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#1.
avg = np.sum(a2)/a2.size

In [ ]:
#2.
np.square(a2-avg)

array([[6.25, 2.25, 0.25],
       [0.25, 2.25, 6.25]])

In [ ]:
#3.
np.mean(np.square(a2-avg))

np.float64(2.9166666666666665)

### Reshape

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.shape,a3.shape

((2, 3), (2, 3, 3))

In [ ]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3)

In [ ]:
new_a2 = a2.reshape(2,3,1)

old `a2` was `(2,3) = (2*3) = 6`

new `a2` was `(2,3,1) = (2*3*1) = 6`

In [ ]:
new_a2 + a3 # now it follows broadcasting rule

array([[[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]],

       [[14, 15, 16],
        [18, 19, 20],
        [22, 23, 24]]])

### Transpose


A tranpose reverses the order of the axes.

For example, an array with shape `(2, 3)` becomes `(3, 2)`.

In [ ]:
a2.shape

(2, 3)

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.T.shape

(3, 2)

For larger arrays, the default value of a tranpose is to swap the first and last axes.

For example, `(5, 3, 3)` -> `(3, 3, 5)`.

In [ ]:
matrix = np.random.randint(1,10,size=(5,3,4))
matrix

array([[[2, 3, 3, 9],
        [4, 7, 2, 3],
        [5, 8, 2, 9]],

       [[3, 5, 7, 8],
        [4, 4, 9, 9],
        [9, 5, 3, 3]],

       [[6, 6, 7, 8],
        [3, 6, 8, 3],
        [4, 6, 2, 3]],

       [[9, 2, 6, 2],
        [3, 1, 7, 1],
        [8, 6, 6, 1]],

       [[8, 3, 4, 5],
        [9, 6, 7, 7],
        [7, 8, 3, 7]]])

In [ ]:
matrix.shape , matrix.ndim

((5, 3, 4), 3)

In [ ]:
matrix.T

array([[[2, 3, 6, 9, 8],
        [4, 4, 3, 3, 9],
        [5, 9, 4, 8, 7]],

       [[3, 5, 6, 2, 3],
        [7, 4, 6, 1, 6],
        [8, 5, 6, 6, 8]],

       [[3, 7, 7, 6, 4],
        [2, 9, 8, 7, 7],
        [2, 3, 2, 6, 3]],

       [[9, 8, 8, 2, 5],
        [3, 9, 3, 1, 7],
        [9, 3, 3, 1, 7]]])

In [ ]:
matrix.T.shape, matrix.T.ndim

((4, 3, 5), 3)

In [ ]:
# check
matrix.shape[::-1] == matrix.T.shape

True

In [ ]:
# Check to see if the first and last axes are swapped
matrix.T == matrix.swapaxes(0, -1) # swap first (0) and last (-1) axes

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

You can see more advanced forms of tranposing in the NumPy documentation under [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html).

### Dot product

The main two rules for dot product to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
  
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

**Note:** In NumPy, `np.dot()` and `@` can be used to acheive the same result for 1-2 dimension arrays. However, their behaviour begins to differ at arrays with 3+ dimensions.

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(10,size=(3,2))

mat1.shape, mat2.shape

((3, 3), (3, 2))

In [ ]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [ ]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]])

In [ ]:
np.dot(mat1,mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [ ]:
mat1 @ mat2 # (however, they may behave differently at 3D+ arrays)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [ ]:
np.random.seed(0)
m3 = np.random.randint(10,size=(4,3))
m4 = np.random.randint(10,size=(4,3))
m3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [ ]:
m4

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [ ]:
m3.shape, m4.shape

((4, 3), (4, 3))

In [ ]:
np.dot(m3,m4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [ ]:
np.dot(m3.T , m4)

array([[118,  96,  77],
       [145, 110, 137],
       [148, 137, 130]])

In [ ]:
# Element-wise multiplication, also known as Hadamard product
m3 * m4

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

### Comparison Operators

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [ ]:
a1 >= a3

array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

## Example:

#### Dot Product practical example - Nut butter Sales

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon","Tues","Wed","Thu","Fri"],
                            columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

      Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thu               4              6             12
Fri               1              6              7

In [ ]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices.shape

(1, 3)

In [ ]:
weekly_sales.shape

(5, 3)

In [ ]:
total_sales = prices.dot(sales_amounts)
total_sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

The shapes aren't aligned, we need the middle two numbers to be the same.

In [ ]:
prices.shape

(3,)

In [ ]:
sales_amounts.T.shape

(3, 5)

In [ ]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [ ]:
butter_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

       Mon  Tues  Wed  Thu  Fri
Price  240   138  458  232  142

In [ ]:
weekly_sales['Total'] = daily_sales.T
weekly_sales

      Almond butter  Peanut butter  Cashew butter  Total
Mon              12             15              0    240
Tues              3              3              7    138
Wed               9             19             18    458
Thu               4              6             12    232
Fri               1              6              7    142


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

## Sorting arrays

*   List item
*   List item



* [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) - sort values in a specified dimension of an array.
* [`np.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) - return the indices to sort the array on a given axis.
* [`np.argmax()`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) - return the index/indicies which gives the highest value(s) along an axis.
* [`np.argmin()`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) - return the index/indices which gives the lowest value(s) along an axis.

In [ ]:
random_array = np.random.randint(10,size=(5,3))
random_array

array([[8, 1, 3],
       [3, 3, 7],
       [0, 1, 9],
       [9, 0, 4],
       [7, 3, 2]])

In [ ]:
np.sort(random_array) # each row is sorted

array([[1, 3, 8],
       [3, 3, 7],
       [0, 1, 9],
       [0, 4, 9],
       [2, 3, 7]])

In [ ]:
random_array_2 = np.random.rand(5,3)
random_array_2

array([[0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  ],
       [0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547],
       [0.66676672, 0.67063787, 0.21038256]])

In [ ]:
np.argsort(random_array_2)

array([[2, 0, 1],
       [1, 2, 0],
       [2, 1, 0],
       [2, 0, 1],
       [2, 0, 1]])

In [ ]:
np.argmax(random_array)

np.int64(8)

In [ ]:
random_array_2 = np.random.rand(5,3,3)
random_array_2

array([[[0.65320082, 0.65210327, 0.43141844],
        [0.8965466 , 0.36756187, 0.43586493],
        [0.89192336, 0.80619399, 0.70388858]],

       [[0.10022689, 0.91948261, 0.7142413 ],
        [0.99884701, 0.1494483 , 0.86812606],
        [0.16249293, 0.61555956, 0.12381998]],

       [[0.84800823, 0.80731896, 0.56910074],
        [0.4071833 , 0.069167  , 0.69742877],
        [0.45354268, 0.7220556 , 0.86638233]],

       [[0.97552151, 0.85580334, 0.01171408],
        [0.35997806, 0.72999056, 0.17162968],
        [0.52103661, 0.05433799, 0.19999652]],

       [[0.01852179, 0.7936977 , 0.22392469],
        [0.34535168, 0.92808129, 0.7044144 ],
        [0.03183893, 0.16469416, 0.6214784 ]]])

In [ ]:
np.argmax(random_array_2)

np.int64(12)

In [ ]:
np.max(random_array_2) #12th index if the matrix was flat

np.float64(0.9988470065678665)

In [ ]:
np.max(random_array)

np.int64(9)

In [ ]:
np.argmax(random_array,axis=1) # Down the vertical

array([0, 2, 2, 0, 0])

In [ ]:
np.argmax(random_array,axis=0) # Across the Horizontal

array([3, 1, 2])


<Br>
<Br>
<Br>

---

<Br>
<Br>
<Br>

# Use Case

In [ ]:
from matplotlib.image import imread

galaxy = imread("/content/images/wallpaper-from-the-last-shot-of-the-season-8-finale-v0-4mw9xjr592gf1.webp")

print(type(galaxy))

<class 'numpy.ndarray'>

In [ ]:
galaxy.shape # (row, col, RGB) 0-255

(607, 1080, 3)

In [ ]:
galaxy

array([[[  3,   3,  30],
        [  3,   3,  30],
        [  3,   3,  30],
        ...,
        [223, 109, 180],
        [225, 114, 181],
        [231, 120, 187]],

       [[  3,   3,  30],
        [  3,   3,  30],
        [  3,   3,  30],
        ...,
        [223, 109, 180],
        [223, 111, 181],
        [226, 115, 184]],

       [[  3,   3,  30],
        [  3,   3,  30],
        [  3,   3,  30],
        ...,
        [222, 107, 182],
        [219, 107, 181],
        [223, 110, 185]],

       ...,

       [[ 10,  12,  27],
        [  6,   8,  23],
        [  3,   5,  20],
        ...,
        [ 42,  55,  87],
        [ 59,  74, 106],
        [ 47,  63,  94]],

       [[  5,   7,  22],
        [  3,   5,  20],
        [  1,   4,  19],
        ...,
        [ 28,  41,  73],
        [ 45,  60,  92],
        [ 35,  50,  81]],

       [[  3,   5,  20],
        [  1,   4,  19],
        [  1,   4,  19],
        ...,
        [ 24,  37,  70],
        [ 42,  57,  88],
        [ 31,  46,  78]]], dtype=uint8)