<a href="https://colab.research.google.com/github/samrat-rm/Brain-Cache/blob/main/Pandas_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

[Learned from this colab notebook](https://colab.research.google.com/github/Nyandwi/machine_learning_complete/blob/main/2_data_manipulation_with_pandas/2_data_manipulation_with_pandas.ipynb#scrollTo=ErLffIn4mD93)

<a name='0'></a>
## 1. Basics of Pandas for data manipulation

### A. Series and DataFrames

Both series and DataFrames are Pandas Data structures.

Series is like one dimensional NumPy array with axis labels.

DataFrame is multidimensional NumPy array with labels on rows and columns.

Working with NumPy, we saw that it supports numeric type data. Pandas on other hand supports whole range of data types, from numeric to strings, etc..

In [2]:
import pandas as pd
import numpy as np

## Creating Series

Series can be created from a Python list, dictionary, and NumPy array.

In [3]:
#list
num = [1,2,3]
pd.Series(num)

0    1
1    2
2    3
dtype: int64

In [4]:
week = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
pd.Series(week)

0    Mon
1    Tue
2    Wed
3    Thu
4    Fri
5    Sat
6    Sun
dtype: object

In [5]:
week = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
pd.Series(week,index=["a","b","c","d","e","f","g"])

a    Mon
b    Tue
c    Wed
d    Thu
e    Fri
f    Sat
g    Sun
dtype: object

Note the data types `int64` and `object` for string.

In [6]:
# dictionary

country_code = {
    1:"US",
    91:"India",
    49:"Germany",
    86:"China",
    250:"Rwanda"
}

pd.Series(country_code)

1           US
91       India
49     Germany
86       China
250     Rwanda
dtype: object

In [7]:
# Numpy Array
arr = np.array([1,2,3,4,5])
pd.Series(arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

If we don't provide the indexes, the default indexes are numbers...starts from 0,1,2..

In [8]:
pd.Series(arr,index=["a","b","c","d","e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64

## DataFrames

DataFrames are the most used Pandas data structure. It can be created from a dictionary, 2D array, and Series.

In [9]:
# Dictionary
countries = {
    "Name":["USA","India","German","Rwanda"] ,
    'Codes':[1,91,49,250]}
pd.DataFrame(countries)

     Name  Codes
0     USA      1
1   India     91
2  German     49
3  Rwanda    250

In [10]:
# Numpy Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
pd.DataFrame(arr,columns=["c1","c2","c3"])

   c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9

In [11]:
country_code = {
    1:"US",
    91:"India",
    49:"Germany",
    86:"China",
    250:"Rwanda"
}

pd_series = pd.Series(country_code)
pd_series

1           US
91       India
49     Germany
86       China
250     Rwanda
dtype: object

In [12]:
df = pd.DataFrame(pd_series,columns=["Codes"])

df

       Codes
1         US
91     India
49   Germany
86     China
250   Rwanda

In [13]:
# Add col
df["Population"] = [100,200,300,250,400]
df

       Codes  Population
1         US         100
91     India         200
49   Germany         300
86     China         250
250   Rwanda         400

In [14]:
# Delete col
df.drop("Population",axis=1)

       Codes
1         US
91     India
49   Germany
86     China
250   Rwanda

In [15]:
df

       Codes  Population
1         US         100
91     India         200
49   Germany         300
86     China         250
250   Rwanda         400

In [16]:
df.columns

Index(['Codes', 'Population'], dtype='object')

In [17]:
df.keys()

Index(['Codes', 'Population'], dtype='object')

In [18]:
df.index

Index([1, 91, 49, 86, 250], dtype='int64')

## Data Indexing, Selection and Iteration

#### Column Selection

In [19]:
countries = {
    "Name":["USA","India","German","Rwanda"] ,
    'Codes':[1,91,49,250]}
df = pd.DataFrame(countries,index=["a","b","c","d"])
df

     Name  Codes
a     USA      1
b   India     91
c  German     49
d  Rwanda    250

In [20]:
df["Name"]

a       USA
b     India
c    German
d    Rwanda
Name: Name, dtype: object

In [21]:
df.Name

a       USA
b     India
c    German
d    Rwanda
Name: Name, dtype: object

In [22]:
df ["Codes"]

a      1
b     91
c     49
d    250
Name: Codes, dtype: int64

In [23]:
# Multiple col
df[["Name","Codes"]]

     Name  Codes
a     USA      1
b   India     91
c  German     49
d  Rwanda    250

#### Row Selection

In [24]:
df[0:2]

    Name  Codes
a    USA      1
b  India     91

In [25]:
df[:2]

    Name  Codes
a    USA      1
b  India     91

You can also use `loc` to select data by the label indexes and `iloc` to select by default integer index (or by the position of the row)

In [26]:
df.loc['a']

Name     USA
Codes      1
Name: a, dtype: object

In [27]:
df.iloc[0]

Name     USA
Codes      1
Name: a, dtype: object

In [28]:
df.loc["b":"d"]

     Name  Codes
b   India     91
c  German     49
d  Rwanda    250

In [29]:
df[:"b"]

    Name  Codes
a    USA      1
b  India     91

In [30]:
df.iloc[2]

Name     German
Codes        49
Name: c, dtype: object

In [31]:
df.iloc[1:3]

     Name  Codes
b   India     91
c  German     49

In [32]:
df.iloc[2:]

     Name  Codes
c  German     49
d  Rwanda    250

#### Conditional Selection

In [33]:
df

     Name  Codes
a     USA      1
b   India     91
c  German     49
d  Rwanda    250

In [34]:
df[df["Codes"]== 49]

     Name  Codes
c  German     49

In [35]:
df[df["Codes"]<250]

     Name  Codes
a     USA      1
b   India     91
c  German     49

In [36]:
df[df["Name"]=="USA"]

  Name  Codes
a  USA      1

You can use and & or | for more than conditions

`df [(condition 1) & (condition 2)]`

In [37]:
df[ (df["Codes"]==91) & (df["Name"]=="India") ]

    Name  Codes
b  India     91

You can also use `isin()` and `where()` to select data in a series or dataframe.

In [38]:
sample_code_names = [1,3,250,"USA","India"]

df.isin(sample_code_names)

    Name  Codes
a   True   True
b   True  False
c  False  False
d  False   True

In [40]:
# mode specific
sample_code_names = {"Codes":[1,3,250] , "Name":["USA","India","England"]}

df.isin(sample_code_names)

    Name  Codes
a   True   True
b   True  False
c  False  False
d  False   True

In [41]:
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]) , columns=['c1','c2','c3'])
df2

   c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9

In [42]:
df2.isin([0,3,5,7])

      c1     c2     c3
0  False  False   True
1  False   True  False
2   True  False  False

In [44]:
df2[df2>4]

    c1   c2   c3
0  NaN  NaN  NaN
1  NaN  5.0  6.0
2  7.0  8.0  9.0

In [46]:
df2.where(df2>4)

    c1   c2   c3
0  NaN  NaN  NaN
1  NaN  5.0  6.0
2  7.0  8.0  9.0

Note: Returns `Nan` not `False`

In [48]:
df2.where(df2>4,0)

   c1  c2  c3
0   0   0   0
1   0   5   6
2   7   8   9

Now this way it returns 0

In [51]:
df2[df2<=4]=0
df2

   c1  c2  c3
0   0   0   0
1   0   0   0
2   0   0   0

## Iteration

```
df.items() #Iterate over (column name, Series) pairs.
DataFrame.iterrows() Iterate over DataFrame rows as (index, Series) pairs.
DataFrame.itertuples([index, name]) Iterate over DataFrame rows as namedtuples.
```

In [55]:
df2 = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]) , columns=['c1','c2','c3'])
df2

   c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9

In [58]:
for col_name, content in df2.items():
  print(col_name)
  print(content)

c1
0    1
1    4
2    7
Name: c1, dtype: int64
c2
0    2
1    5
2    8
Name: c2, dtype: int64
c3
0    3
1    6
2    9
Name: c3, dtype: int64

In [59]:
# Same as df.items()
for col_name, content in df2.iteritems():
  print(col_name)
  print(content)

AttributeError: 'DataFrame' object has no attribute 'iteritems'

`df.iteritms()` is depricated in recent Pandas versions

In [62]:
for row in df2.iterrows():
  print(row,"\n")

(0, c1    1
c2    2
c3    3
Name: 0, dtype: int64)

(1, c1    4
c2    5
c3    6
Name: 1, dtype: int64)

(2, c1    7
c2    8
c3    9
Name: 2, dtype: int64)

In [66]:
for row in df2.itertuples():
  print(row)

Pandas(Index=0, c1=1, c2=2, c3=3)
Pandas(Index=1, c1=4, c2=5, c3=6)
Pandas(Index=2, c1=7, c2=8, c3=9)

`df.itertupels()` is usually the preferred row-looping method because it avoids creating expensive Series objects for every row. Its much faster than `df.iterrows()`

Performnce Ladder:
```
vectorized operations  >>>  itertuples()  >>>  iterrows()
```

## Vectorized operations:
It “operate on the whole column/array at once instead of looping row-by-row.”

Instead of Python touching every row manually, pandas pushes the work down into highly optimized C/NumPy code. That’s why it’s dramatically faster.

## Dealing with Missing data

Real world datasets are messy, often with missing values. Pandas replace NaN with missing values by default. NaN stands for not a number.

Missing values can either be
- ignored
- droped
- or filled

In [71]:
df3 = pd.DataFrame(np.array([[1,2,3],[4,np.nan,6],[7,np.nan,np.nan]]),
                  columns=['c1','c2','c3'])
df3

    c1   c2   c3
0  1.0  2.0  3.0
1  4.0  NaN  6.0
2  7.0  NaN  NaN

#### Checking missing values

In [77]:
# missing values
df3.isnull()

      c1     c2     c3
0  False  False  False
1  False   True  False
2  False   True   True

In [75]:
# calc how many null values in each col
df3.isnull().sum()

c1    0
c2    2
c3    1
dtype: int64

In [76]:
# non missing values
df3.notna()

     c1     c2     c3
0  True   True   True
1  True  False   True
2  True  False  False

In [78]:
df3.notna().sum()

c1    3
c2    1
c3    2
dtype: int64

#### Remiving Mising values

In [79]:
df3.dropna()

    c1   c2   c3
0  1.0  2.0  3.0

All rows are deleted because `dropna()` will remove each (whole row) row which have missing value.

In [81]:
df3['c3'].dropna() # dropping nan in specific col

0    3.0
1    6.0
Name: c3, dtype: float64

Drop data with axis.

> Axis 0 is row and 1 is col

`df.dropna(axis=1)` will delete all columns with nan data. Default axis is 0

In [82]:
df3.dropna(axis=1)

    c1
0  1.0
1  4.0
2  7.0

In [83]:
df3.dropna(axis=0)

    c1   c2   c3
0  1.0  2.0  3.0

### Filling Missing values

In [84]:
df3.fillna(67)

    c1    c2    c3
0  1.0   2.0   3.0
1  4.0  67.0   6.0
2  7.0  67.0  67.0

In [85]:
df.fillna('fillme')

    c1      c2      c3
0  1.0     2.0     3.0
1  4.0  fillme     6.0
2  7.0  fillme  fillme

Notice the string and float datatype. That’s one of the core differences between a NumPy array and a Pandas DataFrame.

NumPy arrays are designed for fast mathematical computation, so they usually store data in a single datatype.NumPy “upcasts” everything to a common type so the array stays uniform. This is why NumPy is extremely fast — memory is tightly packed like identical boxes in a warehouse.

Pandas DataFrames are more like spreadsheets. Each column can have its own datatype.

Internally, Pandas is actually built on top of NumPy. Think of a DataFrame as a collection of multiple NumPy arrays stitched together column-wise.

You can forward `fill (ffill) or backward fill(bfill)`
Or fill a current value with previous or next value

In [86]:
df3.fillna(method="ffill")

/tmp/ipykernel_26382/1781791582.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method="ffill")

    c1   c2   c3
0  1.0  2.0  3.0
1  4.0  2.0  6.0
2  7.0  2.0  6.0

In [88]:
df3.fillna(method="bfill")
# Won't change it because the last values are NaNs, so it backward it

/tmp/ipykernel_26382/1683099377.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method="bfill")

    c1   c2   c3
0  1.0  2.0  3.0
1  4.0  NaN  6.0
2  7.0  NaN  NaN

In [89]:
# If we change the axis to columns, you can see that Nans at row 2 and col 2 is backfilled with 6

df3.fillna(method='bfill', axis='columns')

/tmp/ipykernel_26382/3656475918.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method='bfill', axis='columns')

    c1   c2   c3
0  1.0  2.0  3.0
1  4.0  6.0  6.0
2  7.0  NaN  NaN

In [90]:
df3.fillna(method='ffill', axis='columns')

/tmp/ipykernel_26382/1328881632.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method='ffill', axis='columns')

    c1   c2   c3
0  1.0  2.0  3.0
1  4.0  4.0  6.0
2  7.0  7.0  7.0

## More Operations and Functions

This section will show the more and most useful functions of Pandas.

In [98]:
df4 = pd.DataFrame(
    {
    "Product Name" : ["shirt","Boot","Bag"],
    "Order Number" : [45,43,42],
    "Total Qty" : [10,5,7]
    } ,
    columns = ["Product Name","Order Number","Total Qty"],
    index=["a1",'a2',"a3"])
df4

   Product Name  Order Number  Total Qty
a1        shirt            45         10
a2         Boot            43          5
a3          Bag            42          7

In [99]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a1 to a3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  3 non-null      object
 1   Order Number  3 non-null      int64
 2   Total Qty     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

Note: String is Object dtype in pandas

In [100]:
df4.columns

Index(['Product Name', 'Order Number', 'Total Qty'], dtype='object')

In [107]:
df4.keys()

Index(['Product Name', 'Order Number', 'Total Qty'], dtype='object')

In [102]:
df4.index

Index(['a1', 'a2', 'a3'], dtype='object')

In [103]:
df4.head()

   Product Name  Order Number  Total Qty
a1        shirt            45         10
a2         Boot            43          5
a3          Bag            42          7

In [104]:
df4.head(1)

   Product Name  Order Number  Total Qty
a1        shirt            45         10

In [105]:
df4.tail(1)

   Product Name  Order Number  Total Qty
a3          Bag            42          7

In [108]:
df4.values # without index and column

array([['shirt', 45, 10],
       ['Boot', 43, 5],
       ['Bag', 42, 7]], dtype=object)

In [109]:
df4.size

9

In [112]:
df4.shape # (row,col)

(3, 3)

In [113]:
df4.shape[0] # rows

3

In [114]:
df4.shape[1] # col

3

### Unique Values

In [116]:
# uniqur values in each column
df4["Product Name"].unique()

array(['shirt', 'Boot', 'Bag'], dtype=object)

In [117]:
df4["Product Name"].nunique()

3

In [119]:
# unique values in all col
df4.value_counts()

Product Name  Order Number  Total Qty
Bag           42            7            1
Boot          43            5            1
shirt         45            10           1
Name: count, dtype: int64

### Aplyin a Function to Dataframe

In [120]:
def double_qty(x):
  return x * x

df4['Total Qty'].apply(double_qty)

a1    100
a2     25
a3     49
Name: Total Qty, dtype: int64

In [123]:
# apply annomynous function

df5 = pd.DataFrame([[1,2],[4,5]],columns=["c1",'c2'],index=[1,2])
df5.applymap(lambda x: x*x)

/tmp/ipykernel_26382/2810709203.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df5.applymap(lambda x: x*x)

   c1  c2
1   1   4
2  16  25

## Sorting values

In [125]:
df4

   Product Name  Order Number  Total Qty
a1        shirt            45         10
a2         Boot            43          5
a3          Bag            42          7

In [124]:
df4.sort_values(["Order Number"])

   Product Name  Order Number  Total Qty
a3          Bag            42          7
a2         Boot            43          5
a1        shirt            45         10

In [126]:
df4.sort_values(["Order Number"],ascending=False)

   Product Name  Order Number  Total Qty
a1        shirt            45         10
a2         Boot            43          5
a3          Bag            42          7

## Aggregate Methods

In [131]:
df4

   Product Name  Order Number  Total Qty
a1        shirt            45         10
a2         Boot            43          5
a3          Bag            42          7

In [132]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a1 to a3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  3 non-null      object
 1   Order Number  3 non-null      int64
 2   Total Qty     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [133]:
# stats summary
df4.describe()

       Order Number  Total Qty
count      3.000000   3.000000
mean      43.333333   7.333333
std        1.527525   2.516611
min       42.000000   5.000000
25%       42.500000   6.000000
50%       43.000000   7.000000
75%       44.000000   8.500000
max       45.000000  10.000000

In [134]:
df4.describe().transpose()

              count       mean       std   min   25%   50%   75%   max
Order Number    3.0  43.333333  1.527525  42.0  42.5  43.0  44.0  45.0
Total Qty       3.0   7.333333  2.516611   5.0   6.0   7.0   8.5  10.0

In [135]:
# or
df4.describe().T

              count       mean       std   min   25%   50%   75%   max
Order Number    3.0  43.333333  1.527525  42.0  42.5  43.0  44.0  45.0
Total Qty       3.0   7.333333  2.516611   5.0   6.0   7.0   8.5  10.0

In [140]:
df4["Total Qty"].mean(), df4["Total Qty"].median()

(np.float64(7.333333333333333), 7.0)

In [141]:
df4["Total Qty"].mode()

0     5
1     7
2    10
Name: Total Qty, dtype: int64

In [148]:
# for all cols
df4.min(), df4.max()

(Product Name    Bag
 Order Number     42
 Total Qty         5
 dtype: object,
 Product Name    shirt
 Order Number       45
 Total Qty          10
 dtype: object)

In [149]:
pd.Series(["b","sa","aaaa"]).min()

'aaaa'

Note: For string sorting, min, max are based on the character wise comparison not string length.

In [150]:
df4["Total Qty"].min() , df4["Total Qty"].max()

(5, 10)

In [151]:
df4["Total Qty"].std() , df4["Total Qty"].var()

(2.516611478423583, 6.333333333333333)

In [152]:
df4["Total Qty"].sum() ,df4["Total Qty"].prod()

(np.int64(22), np.int64(350))

## Group By

It involves splitting data into groups and applying function to each group, and combining the result.

In [157]:
df4 = pd.DataFrame({'Product Name':['Shirt','Boot','Bag', 'Ankle', 'Pullover', 'Boot', 'Ankle', 'Tshirt', 'Shirt'],
              'Order Number':[45,56,64, 34, 67, 56, 34, 89, 45],
              'Total Quantity':[10,5,9, 11, 11, 8, 14, 23, 10]},
              columns = ['Product Name', 'Order Number', 'Total Quantity'])
df4

  Product Name  Order Number  Total Quantity
0        Shirt            45              10
1         Boot            56               5
2          Bag            64               9
3        Ankle            34              11
4     Pullover            67              11
5         Boot            56               8
6        Ankle            34              14
7       Tshirt            89              23
8        Shirt            45              10

In [159]:
df4.groupby("Product Name").sum()

              Order Number  Total Quantity
Product Name
Ankle                   68              25
Bag                     64               9
Boot                   112              13
Pullover                67              11
Shirt                   90              20
Tshirt                  89              23

In [160]:
df4.groupby("Product Name").mean()

              Order Number  Total Quantity
Product Name
Ankle                 34.0            12.5
Bag                   64.0             9.0
Boot                  56.0             6.5
Pullover              67.0            11.0
Shirt                 45.0            10.0
Tshirt                89.0            23.0

In [162]:
df4.groupby(["Product Name","Order Number"]).min()

                           Total Quantity
Product Name Order Number
Ankle        34                        11
Bag          64                         9
Boot         56                         5
Pullover     67                        11
Shirt        45                        10
Tshirt       89                        23

You can also use `aggregation()` after groupby.

In [163]:
df4.groupby("Product Name").aggregate(['min',"max","sum","mean"])

             Order Number                Total Quantity
                      min max  sum  mean            min max sum  mean
Product Name
Ankle                  34  34   68  34.0             11  14  25  12.5
Bag                    64  64   64  64.0              9   9   9   9.0
Boot                   56  56  112  56.0              5   8  13   6.5
Pullover               67  67   67  67.0             11  11  11  11.0
Shirt                  45  45   90  45.0             10  10  20  10.0
Tshirt                 89  89   89  89.0             23  23  23  23.0

# Combinging Datasets

## Concatenation

In [172]:
df1 = pd.DataFrame({"Col1":['A','B','C'],"Col2":[1,2,3]},index=['a','b','c'])
df1

  Col1  Col2
a    A     1
b    B     2
c    C     3

In [173]:
df2 = pd.DataFrame({'Col1':['D','E','F'],
                   'Col2':[4,5,6]},
                   index=['d','e','f'])
df2

  Col1  Col2
d    D     4
e    E     5
f    F     6

In [174]:
df3 = pd.DataFrame({'Col1':['G','I','J'],
                   'Col2':[7,8,9]},
                   index=['g', 'i','j'])
df3

  Col1  Col2
g    G     7
i    I     8
j    J     9

In [175]:
pd.concat([df1,df2,df3])

  Col1  Col2
a    A     1
b    B     2
c    C     3
d    D     4
e    E     5
f    F     6
g    G     7
i    I     8
j    J     9

The default axis is `0`. This is how the combined dataframes will look like if we change the `axis to 1`.

In [177]:
pd.concat([df1,df2,df3],axis=1)

  Col1  Col2 Col1  Col2 Col1  Col2
a    A   1.0  NaN   NaN  NaN   NaN
b    B   2.0  NaN   NaN  NaN   NaN
c    C   3.0  NaN   NaN  NaN   NaN
d  NaN   NaN    D   4.0  NaN   NaN
e  NaN   NaN    E   5.0  NaN   NaN
f  NaN   NaN    F   6.0  NaN   NaN
g  NaN   NaN  NaN   NaN    G   7.0
i  NaN   NaN  NaN   NaN    I   8.0
j  NaN   NaN  NaN   NaN    J   9.0

In [179]:
df1.append([df2,df3]) #deprecated

AttributeError: 'DataFrame' object has no attribute 'append'

In [181]:
pd.concat([df1,df2,df3],axis=1,ignore_index=True) # default col name

     0    1    2    3    4    5
a    A  1.0  NaN  NaN  NaN  NaN
b    B  2.0  NaN  NaN  NaN  NaN
c    C  3.0  NaN  NaN  NaN  NaN
d  NaN  NaN    D  4.0  NaN  NaN
e  NaN  NaN    E  5.0  NaN  NaN
f  NaN  NaN    F  6.0  NaN  NaN
g  NaN  NaN  NaN  NaN    G  7.0
i  NaN  NaN  NaN  NaN    I  8.0
j  NaN  NaN  NaN  NaN    J  9.0

## Merging

If you have worked with SQL, what `pd.merge()` does may be familiar. It links data from different sources (different features) and you have a control on the structure of the combined dataset.

*Pandas Merge method(`how`): SQL Join Name : Description*



```
* left : LEFT OUTER JOIN : Use keys or columns from left frame only

* right : RIGHT OUTER JOIN : Use keys or columns from right frame only

* outer : FULL OUTER JOIN : Use union of keys or columns from both frames

* inner : INNER JOIN : Use intersection of keys or columns from both frames
```

In [186]:
df1 = pd.DataFrame({'Name': ['Joe', 'Joshua', 'Jeanne', 'David'],
                        'Role': ['Manager', 'Developer', 'Engineer', 'Scientist']})

df1

     Name       Role
0     Joe    Manager
1  Joshua  Developer
2  Jeanne   Engineer
3   David  Scientist

In [188]:
df2 = pd.DataFrame({'Name': ['David', 'Joshua', 'Joe', 'Jeanne'],
'Year Hired': [2018, 2017, 2020, 2018]})
df2

     Name  Year Hired
0   David        2018
1  Joshua        2017
2     Joe        2020
3  Jeanne        2018

In [187]:
df3 = pd.DataFrame({'Name': ['David', 'Joshua', 'Joe', 'Jeanne'],
'No of Leaves': [15, 3, 10, 12]})
df3

     Name  No of Leaves
0   David            15
1  Joshua             3
2     Joe            10
3  Jeanne            12

In [191]:
pd.merge(df1,df2)

     Name       Role  Year Hired
0     Joe    Manager        2020
1  Joshua  Developer        2017
2  Jeanne   Engineer        2018
3   David  Scientist        2018

### Default Merge Behavior

When `pd.merge()` is called without specifying the `on` parameter, it automatically looks for columns with the same name in both DataFrames and performs an inner join on those common columns.

In the previous example, `df1` and `df2` both had a column named 'Name', so `pd.merge(df1, df2)` used 'Name' as the key to merge the two DataFrames.

In [192]:
pd.merge(df1,df2,on="Name",how="inner")

     Name       Role  Year Hired
0     Joe    Manager        2020
1  Joshua  Developer        2017
2  Jeanne   Engineer        2018
3   David  Scientist        2018

In [193]:
df1 = pd.DataFrame({'col1': ['K0', 'K0', 'K1', 'K2'],
                     'col2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'col1': ['K0', 'K1', 'K1', 'K2'],
                               'col2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [194]:
df1

  col1 col2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [195]:
df2

  col1 col2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [196]:
pd.merge(df1,df2,on=["col1","col2"],how="inner")

  col1 col2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [197]:
pd.merge(df1,df2,on=["col1","col2"],how="outer")

  col1 col2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [198]:
pd.merge(df1,df2,how="right")

  col1 col2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [202]:
pd.merge(df2,df1,how="left") # switch left, right

  col1 col2   C   D    A    B
0   K0   K0  C0  D0   A0   B0
1   K1   K0  C1  D1   A2   B2
2   K1   K0  C2  D2   A2   B2
3   K2   K0  C3  D3  NaN  NaN

Note: If there are 2 common cols then the merge is done on both by default.

In [199]:
pd.merge(df1,df2,how="left")

  col1 col2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

## Joining

Joining is a simple way of combining columns of two dataframes with differnet index.

> Don't confuse with SQL join. That's merge in Pandas.

In [203]:
df1 = pd.DataFrame({"Col1":['A',"B","C"],
                    "Col2":[1,2,3]},
                   index=["a","b","c"])
df1

  Col1  Col2
a    A     1
b    B     2
c    C     3

In [204]:
df2 = pd.DataFrame({'Col3': ['D', 'E', 'F'],
                    'Col4': [14, 14, 16]},
                      index=['a', 'c', 'd'])
df2

  Col3  Col4
a    D    14
c    E    14
d    F    16

In [210]:
df1.join(df2) # all df1 index

  Col1  Col2 Col3  Col4
a    A     1    D  14.0
b    B     2  NaN   NaN
c    C     3    E  14.0

In [209]:
df2.join(df1) # all df2 index

  Col3  Col4 Col1  Col2
a    D    14    A   1.0
c    E    14    C   3.0
d    F    16  NaN   NaN

Note: The row alignment is on the index.

In [208]:
df2.join(df1,how="inner") # commoon index

  Col3  Col4 Col1  Col2
a    D    14    A     1
c    E    14    C     3

In [211]:
df2.join(df1,how="outer") # all index

  Col3  Col4 Col1  Col2
a    D  14.0    A   1.0
b  NaN   NaN    B   2.0
c    E  14.0    C   3.0
d    F  16.0  NaN   NaN

# Working with CSV and Excel

In [212]:
# Download csv

!curl -O https://raw.githubusercontent.com/nyandwi/public_datasets/master/housing.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1390k  100 1390k    0     0  3336k      0 --:--:-- --:--:-- --:--:-- 3333k

In [214]:
data = pd.read_csv("housing.csv")
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [220]:
data.to_csv("housing_copy.csv",index=False)

In [221]:
data.to_excel("housing_copy.xlsx",index=False)

In [222]:
excel_data = pd.read_excel("housing_copy.xlsx")
excel_data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY

##### Exploring Data

In [215]:
type(data)

pandas.core.frame.DataFrame

In [216]:
data.ndim, data.shape

(2, (20640, 10))

In [217]:
data.index

RangeIndex(start=0, stop=20640, step=1)

In [219]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [224]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [226]:
data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [229]:
data[['total_bedrooms',"total_rooms"]].nunique()

total_bedrooms    1923
total_rooms       5926
dtype: int64

In [231]:
data['total_bedrooms'].unique()

array([ 129., 1106.,  190., ..., 3008., 1857., 1052.])

In [234]:
data['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [235]:
data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [237]:
data.groupby("ocean_proximity").mean()[['total_rooms','total_bedrooms']]

                 total_rooms  total_bedrooms
ocean_proximity
<1H OCEAN        2628.343586      546.539185
INLAND           2717.742787      533.881619
ISLAND           1574.600000      420.400000
NEAR BAY         2493.589520      514.182819
NEAR OCEAN       2583.700903      538.615677

<a name='0'></a>

### [BACK TO TOP](#0)

## More Advanced Data Manipulation Topics

### Reshaping Data

Reshaping data involves changing the layout of a DataFrame. This is often necessary when preparing data for analysis or visualization. Key methods include `pivot_table` (for summarizing data) and `melt` (for unpivoting data).

In [241]:
data = {'City': ['New York', 'New York', 'London', 'London', 'Paris', 'Paris'],
        'Year': [2020, 2021, 2020, 2021, 2020, 2021],
        'Sales': [100, 120, 80, 95, 110, 130]}
df_sales = pd.DataFrame(data)
display(df_sales)

pivoted_sales = df_sales.pivot_table(index='City', columns='Year', values='Sales')
display(pivoted_sales)

       City  Year  Sales
0  New York  2020    100
1  New York  2021    120
2    London  2020     80
3    London  2021     95
4     Paris  2020    110
5     Paris  2021    130

Year       2020   2021
City
London     80.0   95.0
New York  100.0  120.0
Paris     110.0  130.0

`pd.melt()` is basically the opposite direction of a pivot.

In [243]:
data = {'Product': ['A', 'B'],
        'Q1': [100, 150],
        'Q2': [120, 140],
        'Q3': [110, 160],
        'Q4': [130, 170]}
df_quarters = pd.DataFrame(data)
df_quarters.set_index('Product', inplace=True)
display(df_quarters)

melted_quarters = df_quarters.melt(var_name='Quarter', value_name='Sales', ignore_index=False)
display(melted_quarters)

          Q1   Q2   Q3   Q4
Product
A        100  120  110  130
B        150  140  160  170

        Quarter  Sales
Product
A            Q1    100
B            Q1    150
A            Q2    120
B            Q2    140
A            Q3    110
B            Q3    160
A            Q4    130
B            Q4    170

- Use pivot when:
  - “You want to SEE categories as columns.”
  - Human reading/reporting

- Use melt when:
  - “You want to TURN columns into rows.”
  - Analysis/groupby/ml

Super simple memory trick:

* Pivot = “make data wider”
* Melt = “make data longer”

### Handling Duplicates

Duplicate rows can skew your analysis. Pandas provides convenient methods to identify and remove them.

In [244]:
data = {'A': [1, 2, 2, 3, 4, 4],
        'B': ['x', 'y', 'y', 'z', 'w', 'w']}
df_duplicates = pd.DataFrame(data)
display(df_duplicates)

print("\nChecking for duplicates:")
display(df_duplicates.duplicated())

print("\nDataFrame after dropping duplicates:")
display(df_duplicates.drop_duplicates())

   A  B
0  1  x
1  2  y
2  2  y
3  3  z
4  4  w
5  4  w

Checking for duplicates:

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

DataFrame after dropping duplicates:

   A  B
0  1  x
1  2  y
3  3  z
4  4  w

## String Operations

Pandas provides a rich set of string methods that are highly optimized for working with text data in Series and DataFrames. These methods are accessed via the `.str` accessor.

In [245]:
# Create a sample Series with string data
products = pd.Series(['  Apple  ', ' Banana', 'cherry ', 'Date', 'elderberry'])
display(products)

0       Apple
1        Banana
2       cherry
3          Date
4    elderberry
dtype: object

### Case Conversion: `.str.lower()` and `.str.upper()`

These methods convert all characters in the strings to lowercase or uppercase, respectively.

In [246]:
print("Lowercase:")
display(products.str.lower())

print("\nUppercase:")
display(products.str.upper())

Lowercase:

0       apple
1        banana
2       cherry
3          date
4    elderberry
dtype: object

Uppercase:

0       APPLE
1        BANANA
2       CHERRY
3          DATE
4    ELDERBERRY
dtype: object

### String Length: `.str.len()`

Returns the length of each string.

In [247]:
print("String Lengths:")
display(products.str.len())

String Lengths:

0     9
1     7
2     7
3     4
4    10
dtype: int64

### Checking for Substrings: `.str.contains()`

Checks if a substring is present in each string and returns a boolean Series.

In [248]:
print("Contains 'a':")
display(products.str.contains('a', case=False)) # case=False for case-insensitive search

Contains 'a':

0     True
1     True
2    False
3     True
4    False
dtype: bool

### Replacing Substrings: `.str.replace()`

Replaces occurrences of a specified substring with another string.

In [249]:
print("Replacing 'a' with 'X':")
display(products.str.replace('a', 'X', case=False))

Replacing 'a' with 'X':

0       Xpple
1        BXnXnX
2       cherry
3          DXte
4    elderberry
dtype: object

### Splitting Strings: `.str.split()`

Splits strings into lists of substrings based on a delimiter.

In [250]:
sentence = pd.Series(['Hello World', 'Python is fun'])
print("Splitting by space:")
display(sentence.str.split(' '))

Splitting by space:

0       [Hello, World]
1    [Python, is, fun]
dtype: object

### Checking Start/End of Strings: `.str.startswith()` and `.str.endswith()`

Returns a boolean Series indicating whether each string starts or ends with a specified substring.

In [251]:
print("Starts with 'A':")
display(products.str.startswith('A', na=False))

print("\nEnds with 'y':")
display(products.str.endswith('y', na=False))

Starts with 'A':

0    False
1    False
2    False
3    False
4    False
dtype: bool

Ends with 'y':

0    False
1    False
2    False
3    False
4     True
dtype: bool

### Removing Whitespace: `.str.strip()`

Removes leading and trailing whitespace from strings.

In [252]:
print("Before stripping:")
display(products)

print("\nAfter stripping:")
display(products.str.strip())

Before stripping:

0       Apple
1        Banana
2       cherry
3          Date
4    elderberry
dtype: object

After stripping:

0         Apple
1        Banana
2        cherry
3          Date
4    elderberry
dtype: object

## Datetime Operations

Working with dates and times is a common task in data analysis. Pandas provides powerful tools to handle datetime objects, allowing for easy extraction of components, resampling, and time-series manipulations.

In [ ]:
# Create a sample Series with datetime data
dates = pd.Series(pd.to_datetime(['2023-01-01', '2023-01-02 10:30:00', '2023-01-03 14:00:00', '2023-01-04 08:45:15']))
display(dates)

### Extracting Datetime Components

Access various components of datetime objects using the `.dt` accessor.

In [ ]:
print("Year:")
display(dates.dt.year)

print("\nMonth:")
display(dates.dt.month)

print("\nDay:")
display(dates.dt.day)

print("\nHour:")
display(dates.dt.hour)

print("\nDay of week (Monday=0, Sunday=6):")
display(dates.dt.dayofweek)

print("\nName of day of week:")
display(dates.dt.day_name())

### Resampling Time Series Data

Resampling is useful for changing the frequency of time-series data (e.g., from daily to weekly sums).

In [ ]:
# Create a DataFrame with a datetime index and some values
np.random.seed(42)
dates_index = pd.date_range(start='2023-01-01', periods=10, freq='D')
time_series_df = pd.DataFrame({'Value': np.random.randint(10, 100, size=10)}, index=dates_index)
display(time_series_df)

print("\nWeekly Sums (resampled to 'W' for week):")
display(time_series_df.resample('W').sum())

print("\nMonthly Means (resampled to 'M' for month):")
display(time_series_df.resample('M').mean())

### Time Series Shifting

`shift()` moves data forwards or backwards in time, useful for calculating differences or lagging values.

In [ ]:
print("Original:")
display(time_series_df)

print("\nShifted by 1 period (lag):")
display(time_series_df.shift(1))

print("\nDifference from previous day:")
display(time_series_df - time_series_df.shift(1))

### Creating Datetime Index

You can easily create a `DatetimeIndex` which is crucial for time-series analysis.

In [ ]:
date_range = pd.date_range(start='2023-01-01', end='2023-01-05', freq='H')
display(date_range)

# Create a Series with this index
daily_data = pd.Series(range(len(date_range)), index=date_range)
display(daily_data.head())

## Data Type Conversion: `.astype()`

Explicitly converting data types is a critical step in data cleaning and preparation. It ensures that columns are stored efficiently and behave as expected for analysis or machine learning models.

In [253]:
data = {'Value': ['1', '2', '3', '4', '5'], 'Category': ['A', 'B', 'A', 'C', 'B']}
df_types = pd.DataFrame(data)
display(df_types.info())

# Convert 'Value' column to integer type
df_types['Value'] = df_types['Value'].astype(int)
display(df_types.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Value     5 non-null      object
 1   Category  5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Value     5 non-null      int64
 1   Category  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

None

## Categorical Data

Pandas has a dedicated `Categorical` data type which is very useful for columns with a limited number of unique values (e.g., 'Gender', 'City'). It can save memory and improve performance for certain operations, and is crucial for many machine learning models that require numerical inputs.

In [254]:
# Convert 'Category' column to categorical type
df_types['Category'] = df_types['Category'].astype('category')
display(df_types.info())

print("\nCategorical codes:")
display(df_types['Category'].cat.codes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Value     5 non-null      int64
 1   Category  5 non-null      category
dtypes: category(1), int64(1)
memory usage: 309.0 bytes

None

Categorical codes:

0    0
1    1
2    0
3    2
4    1
dtype: int8

## Data Binning (Discretization): `pd.cut()` and `pd.qcut()`

Binning transforms continuous numerical data into discrete categories or bins. This is a common feature engineering technique, especially when the exact numerical value is less important than the range it falls into.

### `pd.cut()`: Binning into fixed-width bins

Use `pd.cut()` when you have specific bin boundaries in mind.

In [255]:
data = {'Age': [5, 12, 18, 25, 35, 45, 60, 75, 80, 90]}
df_age = pd.DataFrame(data)

bins = [0, 12, 18, 35, 60, 100] # Define bin edges
labels = ['Child', 'Adolescent', 'Young Adult', 'Adult', 'Senior'] # Define labels for bins

df_age['Age Group'] = pd.cut(df_age['Age'], bins=bins, labels=labels, right=False) # right=False means [lower, upper)
display(df_age)

   Age    Age Group
0    5        Child
1   12   Adolescent
2   18  Young Adult
3   25  Young Adult
4   35        Adult
5   45        Adult
6   60       Senior
7   75       Senior
8   80       Senior
9   90       Senior

### `pd.qcut()`: Binning into quantiles

Use `pd.qcut()` when you want each bin to have roughly the same number of observations.

In [256]:
data = {'Score': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]}
df_score = pd.DataFrame(data)

df_score['Score Quartile'] = pd.qcut(df_score['Score'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
display(df_score)

   Score Score Quartile
0     10             Q1
1     20             Q1
2     30             Q1
3     40             Q2
4     50             Q2
5     60             Q3
6     70             Q3
7     80             Q4
8     90             Q4
9    100             Q4

## Window Functions: `.rolling()` and `.expanding()`

Window functions are powerful for calculating aggregate statistics over a defined window (or moving range) of data. They are crucial for time-series analysis and creating features like moving averages or cumulative sums.

### `rolling()`: Moving Window Calculations

Applies a function over a fixed-size sliding window.

In [258]:
data = {'Sales': [10, 12, 15, 11, 13, 16, 14, 18, 20]}
df_daily_sales = pd.DataFrame(data)

# Calculate a 3-day rolling mean
df_daily_sales['3-Day Rolling Mean'] = df_daily_sales['Sales'].rolling(window=3).mean()
display(df_daily_sales)

   Sales  3-Day Rolling Mean
0     10                 NaN
1     12                 NaN
2     15           12.333333
3     11           12.666667
4     13           13.000000
5     16           13.333333
6     14           14.333333
7     18           16.000000
8     20           17.333333

### `expanding()`: Expanding Window Calculations

Applies a function over an expanding window, starting from the beginning of the Series/DataFrame up to the current point.

In [259]:
data = {'Value': [1, 2, 3, 4, 5, 6, 7]}
df_expanding = pd.DataFrame(data)

# Calculate a cumulative sum (expanding sum)
df_expanding['Cumulative Sum'] = df_expanding['Value'].expanding().sum()
display(df_expanding)

   Value  Cumulative Sum
0      1             1.0
1      2             3.0
2      3             6.0
3      4            10.0
4      5            15.0
5      6            21.0
6      7            28.0

## Clarifying `map` vs `apply` vs `applymap`

It's important to understand the differences between these methods for applying functions in Pandas, especially considering performance and intended use cases.

### `Series.map()`

*   **Purpose:** Element-wise transformation on a `Series`.
*   **Input:** A dictionary, Series, or a function.
*   **Best for:** Mapping values from one set to another (e.g., `{'old_val': 'new_val'}`) or applying a simple function to each element of a Series.
*   **Performance:** Generally very fast for mappings.

In [260]:
s = pd.Series([1, 2, 3, 4])
mapping_dict = {1: 'One', 2: 'Two'}

print("Using map with a dictionary:")
display(s.map(mapping_dict))

print("\nUsing map with a function:")
display(s.map(lambda x: x * 10))

Using map with a dictionary:

0    One
1    Two
2    NaN
3    NaN
dtype: object

Using map with a function:

0    10
1    20
2    30
3    40
dtype: int64

### `DataFrame.apply()`

*   **Purpose:** Apply a function along an axis of the DataFrame.
*   **Input:** A function.
*   **Best for:** Applying a function to each column (`axis=0`, default) or each row (`axis=1`). The function receives a `Series` (either a column or a row) as input.
*   **Performance:** Faster than looping, but can be slower than vectorized operations or `apply` for element-wise tasks.

In [261]:
df_example = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})
display(df_example)

print("\nApply sum to each column:")
display(df_example.apply(sum))

print("\nApply max to each row:")
display(df_example.apply(max, axis=1))

   A   B
0  1  10
1  2  20
2  3  30

Apply sum to each column:

A     6
B    60
dtype: int64

Apply max to each row:

0    10
1    20
2    30
dtype: int64

### `DataFrame.map()`

*   **Purpose:** Element-wise transformation on an entire DataFrame.
*   **Input:** A function.
*   **`applymap()` (DEPRECATED):** Was used for element-wise operations across the entire DataFrame.
*   **`DataFrame.map()` (RECOMMENDED):** As of Pandas 2.0, `DataFrame.map()` is the recommended method for element-wise operations on a DataFrame, replacing the functionality of `applymap()` and offering better performance in some cases.

In [262]:
df_example = pd.DataFrame({'A': [1, 2, 3], 'B': [10, 20, 30]})
display(df_example)

print("\nUsing DataFrame.map() for element-wise square:")
display(df_example.map(lambda x: x*x))

   A   B
0  1  10
1  2  20
2  3  30

Using DataFrame.map() for element-wise square:

   A    B
0  1  100
1  4  400
2  9  900